SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comment_Mentions](
	[MentionID] [int] IDENTITY(1,1) NOT NULL,
	[CommentID] [int] NULL,
	[MentionedUserID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MentionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Comment_Mentions]  WITH CHECK ADD FOREIGN KEY([MentionedUserID])
REFERENCES [dbo].[Users] ([userID])
GO
