SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Search_Field_Labels](
	[FieldKey] [varchar](100) NOT NULL,
	[EnglishLabel] [nvarchar](200) NOT NULL,
	[GermanLabel] [nvarchar](200) NULL,
	[FrenchLabel] [nvarchar](200) NULL,
	[ItalianLabel] [nvarchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[FieldKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
