SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[userID] [int] IDENTITY(1001,1) NOT NULL,
	[username] [nvarchar](50) NULL,
	[password] [nvarchar](255) NULL,
	[Fullname] [nvarchar](255) NULL,
	[Email] [nvarchar](255) NULL,
	[company] [nvarchar](100) NULL,
	[accessid] [int] NULL,
	[organizationCode] [nvarchar](5) NULL,
	[InitReset] [bit] NULL,
	[twoFA] [bit] NULL,
	[twoFASecret] [nvarchar](100) NULL,
 CONSTRAINT [PK__Users__CB9A1CDF7F8A761C] PRIMARY KEY CLUSTERED 
(
	[userID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_EMAIL] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_USERNAME] UNIQUE NONCLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD FOREIGN KEY([accessid])
REFERENCES [dbo].[AccessProfile] ([AccessID])
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [organizationCode] FOREIGN KEY([organizationCode])
REFERENCES [dbo].[Organizations] ([organizationcode])
GO
ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [organizationCode]
GO
