SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Workitem_Tags](
	[WorkitemTagID] [int] IDENTITY(1,1) NOT NULL,
	[WorkitemId] [nvarchar](50) NOT NULL,
	[TagID] [int] NOT NULL,
 CONSTRAINT [PK_Workitem_Tags] PRIMARY KEY CLUSTERED 
(
	[WorkitemTagID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Workitem_Tags_Barcode_TagID] UNIQUE NONCLUSTERED 
(
	[WorkitemId] ASC,
	[TagID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [IX_Workitem_Tags_Barcode] ON [dbo].[Workitem_Tags]
(
	[WorkitemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Workitem_Tags]  WITH CHECK ADD  CONSTRAINT [FK_Workitem_Tags_Tags] FOREIGN KEY([TagID])
REFERENCES [dbo].[Tags] ([TagID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Workitem_Tags] CHECK CONSTRAINT [FK_Workitem_Tags_Tags]
GO
