"""The phone quick entry's "Undo" on Base Services (#354).

POST /api/generali/baseservices/<id>/undo is generated by ``_crud`` for tables
that opt in (``CrudTable.undo``). Same contract as Reporting's hand-written
undo: only the caller's OWN entry, only within UNDO_WINDOW_SECONDS, only with
``.add`` -- most Generali users hold add but no delete, and this must not
become a back door to deleting anyone else's hours.

Also covers the add endpoint handing back the new row's id, which is what the
pill needs to offer Undo at all.

Seams as in test_generali_reporting_undo.py: permissions patched at
hooks.load_permissions_for_user, the Generali engine replaced by a fake that
interprets the endpoints' SQL shapes.
"""

from datetime import date

import pytest

import nx_lib.hooks as hooks
import nx_lib.views.generali as gv
from nx_lib.views.generali._crud import UNDO_WINDOW_SECONDS

TABLE = "[Generali].[dbo].[BaseServiceEntries]"


class _FakeCursor:
    def __init__(self, rows, log):
        self._rows, self._log, self._result = rows, log, []

    def execute(self, sql, params=None):
        params = list(params or [])
        normalized = " ".join(sql.split())
        self._log.append((normalized, params))
        if normalized.startswith("SELECT UserID, DATEDIFF"):
            r = self._rows.get(params[0])
            self._result = [(r["owner"], r["age"])] if r else []
        elif normalized.startswith(f"DELETE FROM {TABLE}"):
            rid, uid = params
            if rid in self._rows and str(self._rows[rid]["owner"]) == str(uid):
                del self._rows[rid]
            self._result = []
        elif normalized.startswith(f"INSERT INTO {TABLE}"):
            new_id = max(self._rows, default=0) + 1
            self._rows[new_id] = {"owner": params[1], "age": 0}
            self._result = [(new_id,)]
        else:
            self._result = []

    def fetchone(self):
        return self._result[0] if self._result else None

    def fetchall(self):
        return self._result

    def close(self):
        pass


class _FakeConn:
    def __init__(self, cur):
        self._cur = cur

    def cursor(self):
        return self._cur

    def commit(self):
        pass

    def close(self):
        pass


class _FakeEngine:
    def __init__(self, rows, log):
        self._rows, self._log = rows, log

    def raw_connection(self):
        return _FakeConn(_FakeCursor(self._rows, self._log))


PERMS = ["tenant.generali.baseservices.view", "tenant.generali.baseservices.add"]


@pytest.fixture()
def wired(user_client, monkeypatch):
    with user_client.session_transaction() as sess:
        me = sess["userid"]
    rows = {
        1: {"owner": me, "age": 30},  # mine, fresh
        2: {"owner": f"other-{me}", "age": 30},  # someone else's
        3: {"owner": me, "age": UNDO_WINDOW_SECONDS + 1},  # mine, too old
    }
    log = []
    monkeypatch.setattr(gv, "engine_generali_db", _FakeEngine(rows, log))
    monkeypatch.setattr(hooks, "load_permissions_for_user", lambda uid: PERMS)
    return me, rows, log


def test_undo_deletes_my_fresh_entry(user_client, wired):
    _, rows, log = wired
    resp = user_client.post("/api/generali/baseservices/1/undo")
    assert resp.status_code == 200 and resp.get_json()["success"] is True
    assert 1 not in rows
    # the DELETE itself is scoped to the caller too, not just the check before it
    assert any(sql.startswith("DELETE") and "UserID = ?" in sql for sql, _ in log)


def test_undo_refuses_someone_elses_entry(user_client, wired):
    _, rows, _ = wired
    resp = user_client.post("/api/generali/baseservices/2/undo")
    assert resp.status_code == 403
    assert 2 in rows


def test_undo_refuses_after_the_window(user_client, wired):
    _, rows, _ = wired
    resp = user_client.post("/api/generali/baseservices/3/undo")
    assert resp.status_code == 409
    assert 3 in rows


def test_undo_of_a_missing_entry_is_404(user_client, wired):
    resp = user_client.post("/api/generali/baseservices/99/undo")
    assert resp.status_code == 404


def test_undo_needs_the_add_permission(user_client, wired, monkeypatch):
    _, rows, _ = wired
    monkeypatch.setattr(
        hooks, "load_permissions_for_user", lambda uid: ["tenant.generali.baseservices.view"]
    )
    resp = user_client.post("/api/generali/baseservices/1/undo")
    assert resp.status_code in (302, 403)
    assert 1 in rows


def test_add_returns_the_new_id(user_client, wired):
    me, rows, log = wired
    resp = user_client.post(
        "/api/generali/baseservices",
        json={
            "forDate": date.today().isoformat(),
            "category": "PPR",
            "effortInHours": 1.5,
        },
    )
    body = resp.get_json()
    assert resp.status_code == 200 and body["success"] is True
    assert body["id"] == 4
    assert str(rows[4]["owner"]) == str(me)
    assert any("OUTPUT INSERTED.ID" in sql for sql, _ in log)


def test_tables_without_undo_get_no_route(app):
    """Undo is opt-in: Reporting keeps its own hand-written one, and the other
    CRUD tables have none until they get a phone quick entry."""
    rules = {r.rule for r in app.url_map.iter_rules()}
    assert "/api/generali/baseservices/<int:record_id>/undo" in rules
    assert "/api/generali/pdqm/<int:record_id>/undo" not in rules
    assert "/api/generali/projectmanagement/<int:record_id>/undo" not in rules
