SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF
GO
CREATE NONCLUSTERED INDEX [IX_MOBSCN_CLIENT_NexoraDocFieldSearch] ON [dbo].[MOBSCN_CLIENT]
(
	[WorkitemID] ASC,
	[DatumImportiert] ASC,
	[DatumLieferung] ASC
)
INCLUDE(ScanBatchNr, PID, ScanArchivBoxNr, PersonenAkteID, AnstellungsAkteID, DokArtIDZielsystem,
DokArtIDSydoc, DokArtName, DokDatum, RegisterIDZielsystem, StammdatenDeckblattTyp, StammdatenGeburtsdatum,
StammdatenVorname, StammdatenNachname, StammdatenTrennblattID, ZielsystemDateiname) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
