-- 0076: seed ColumnType / IdColumnType from live target DBs (#98).
-- Generated by scripts/seed_column_types.py against StatisticsDB INFORMATION_SCHEMA.COLUMNS (default client) and the MS02 doc-field Postgres DB's information_schema.columns (ms02 client), read-only.
-- Unresolvable table/column pairs are left as comments (NULL stays NULL), which keeps the legacy CAST/::text predicate path (Task 12).
-- Generated: 2026-08-26T23:21:17.611842+00:00

-- ProcessSources.IdColumnType
UPDATE dbo.ProcessSources SET IdColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'compass.01_Invoice_SAP';
UPDATE dbo.ProcessSources SET IdColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'elektromaterial.02_Invoice';
UPDATE dbo.ProcessSources SET IdColumnType = 'numeric' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_InitialScan';
UPDATE dbo.ProcessSources SET IdColumnType = 'int' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_Posteingang';
UPDATE dbo.ProcessSources SET IdColumnType = 'int' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New';
UPDATE dbo.ProcessSources SET IdColumnType = 'character varying' WHERE ClientCode = 'ms02' AND ProcessName = 'sydoc.05_PDBS';
GO

-- ProcessFieldMappings.ColumnType
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'compass.01_Invoice_SAP' AND FieldKey = 'bankpk';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'compass.01_Invoice_SAP' AND FieldKey = 'crdname';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'compass.01_Invoice_SAP' AND FieldKey = 'crdno';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'compass.01_Invoice_SAP' AND FieldKey = 'docbarcode';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'compass.01_Invoice_SAP' AND FieldKey = 'doccurrency';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'date' WHERE ClientCode = 'default' AND ProcessName = 'compass.01_Invoice_SAP' AND FieldKey = 'docdate';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'compass.01_Invoice_SAP' AND FieldKey = 'docsource';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'compass.01_Invoice_SAP' AND FieldKey = 'doctype';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'compass.01_Invoice_SAP' AND FieldKey = 'grossamount';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'compass.01_Invoice_SAP' AND FieldKey = 'invoicenr';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'compass.01_Invoice_SAP' AND FieldKey = 'netamount';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'int' WHERE ClientCode = 'default' AND ProcessName = 'compass.01_Invoice_SAP' AND FieldKey = 'pagecount';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'compass.01_Invoice_SAP' AND FieldKey = 'targetsystemfilename';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'compass.01_Invoice_SAP' AND FieldKey = 'validationuser';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'compass.01_Invoice_SAP' AND FieldKey = 'vatamount';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'elektromaterial.02_Invoice' AND FieldKey = 'bankpk';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'elektromaterial.02_Invoice' AND FieldKey = 'branch';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'elektromaterial.02_Invoice' AND FieldKey = 'crdname';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'elektromaterial.02_Invoice' AND FieldKey = 'crdno';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'elektromaterial.02_Invoice' AND FieldKey = 'docbarcode';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'elektromaterial.02_Invoice' AND FieldKey = 'doccurrency';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'date' WHERE ClientCode = 'default' AND ProcessName = 'elektromaterial.02_Invoice' AND FieldKey = 'docdate';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'elektromaterial.02_Invoice' AND FieldKey = 'docsource';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'elektromaterial.02_Invoice' AND FieldKey = 'doctype';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'elektromaterial.02_Invoice' AND FieldKey = 'emailfromaddress';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'elektromaterial.02_Invoice' AND FieldKey = 'grossamount';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'elektromaterial.02_Invoice' AND FieldKey = 'invoicenr';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'elektromaterial.02_Invoice' AND FieldKey = 'netamount';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'elektromaterial.02_Invoice' AND FieldKey = 'ordernumber';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'int' WHERE ClientCode = 'default' AND ProcessName = 'elektromaterial.02_Invoice' AND FieldKey = 'pagecount';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'elektromaterial.02_Invoice' AND FieldKey = 'targetsystemfilename';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'elektromaterial.02_Invoice' AND FieldKey = 'vatamount';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'int' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_InitialScan' AND FieldKey = 'archiveboxno';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_InitialScan' AND FieldKey = 'docbarcode';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_InitialScan' AND FieldKey = 'docid';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_InitialScan' AND FieldKey = 'ownernr';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_InitialScan' AND FieldKey = 'pagecount';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'bigint' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_InitialScan' AND FieldKey = 'propertynr';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_InitialScan' AND FieldKey = 'separatorsheet';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'text' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_InitialScan' AND FieldKey = 'targetsystemfilename';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_InitialScan' AND FieldKey = 'tenancynr';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_Posteingang' AND FieldKey = 'branch';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_Posteingang' AND FieldKey = 'confidentiality';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_Posteingang' AND FieldKey = 'department';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_Posteingang' AND FieldKey = 'docbarcode';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_Posteingang' AND FieldKey = 'docdate';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_Posteingang' AND FieldKey = 'doctype';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_Posteingang' AND FieldKey = 'forwarding';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_Posteingang' AND FieldKey = 'ownernr';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'int' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_Posteingang' AND FieldKey = 'pagecount';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_Posteingang' AND FieldKey = 'postcode';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_Posteingang' AND FieldKey = 'propertynr';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_Posteingang' AND FieldKey = 'recipient';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_Posteingang' AND FieldKey = 'registered';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_Posteingang' AND FieldKey = 'targetsystemfilename';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.02_Posteingang' AND FieldKey = 'tenancynr';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'bankpk';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'client';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'crdname';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'crdno';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'docbarcode';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'doccurrency';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'docsource';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'doctype';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'emailfromaddress';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'esrreference';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'grossamount';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'invoicenr';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'int' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'istec';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'netamount';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'ordernumber';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'ownernr';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'int' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'pagecount';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'propertynr';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'targetsystemfilename';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'nvarchar' WHERE ClientCode = 'default' AND ProcessName = 'privera.03_Invoice_New' AND FieldKey = 'vatamount';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'character varying' WHERE ClientCode = 'ms02' AND ProcessName = 'sydoc.05_PDBS' AND FieldKey = 'archiveboxno';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'character varying' WHERE ClientCode = 'ms02' AND ProcessName = 'sydoc.05_PDBS' AND FieldKey = 'batchname';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'character varying' WHERE ClientCode = 'ms02' AND ProcessName = 'sydoc.05_PDBS' AND FieldKey = 'docbarcode';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'bigint' WHERE ClientCode = 'ms02' AND ProcessName = 'sydoc.05_PDBS' AND FieldKey = 'dossierpositioninbatch';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'bigint' WHERE ClientCode = 'ms02' AND ProcessName = 'sydoc.05_PDBS' AND FieldKey = 'pagecount';
UPDATE dbo.ProcessFieldMappings SET ColumnType = 'character varying' WHERE ClientCode = 'ms02' AND ProcessName = 'sydoc.05_PDBS' AND FieldKey = 'pid';
GO
