-- 0088_permission_rename.sql (#238 phase 3) -- generated by scripts/rename_permissions.py --emit-sql
-- Renames codes to <area>.<object>.<action>[.<scope>] and rewrites descriptions.
-- Grants ride on PermissionID. Data-driven: codes absent on this server are skipped.
DECLARE @map TABLE (OldCode SYSNAME PRIMARY KEY, NewCode SYSNAME, NewDescription NVARCHAR(200));
INSERT INTO @map VALUES
    (N'admin.view', N'admin.view', N'View the admin area'),
    (N'admin.view.users', N'admin.users.view', N'View users'),
    (N'admin.create.user', N'admin.users.add', N'Add users'),
    (N'admin.edit.user', N'admin.users.edit', N'Edit users'),
    (N'admin.delete.user', N'admin.users.delete', N'Delete users'),
    (N'admin.edit.user.override', N'admin.users.overrides.edit', N'Edit per-user permission overrides'),
    (N'admin.view.accessprofiles.useroverrides', N'admin.profiles.view', N'View access profiles and the permissions grid'),
    (N'admin.edit.accessprofile', N'admin.profiles.edit', N'Edit access profiles and their grants'),
    (N'admin.view.organizations', N'admin.organizations.view', N'View organizations'),
    (N'admin.add.organization', N'admin.organizations.add', N'Add organizations'),
    (N'admin.edit.organization', N'admin.organizations.edit', N'Edit organizations'),
    (N'admin.delete.organization', N'admin.organizations.delete', N'Delete organizations'),
    (N'admin.edit.organization.branding', N'admin.organizations.branding.edit', N'Edit organization branding'),
    (N'admin.view.clients', N'admin.clients.view', N'View the client registry'),
    (N'admin.edit.clients', N'admin.clients.edit', N'Edit the client registry'),
    (N'admin.view.processes', N'admin.processes.view', N'View process source mappings'),
    (N'admin.edit.processes', N'admin.processes.edit', N'Edit process source mappings (high trust)'),
    (N'admin.view.active.sessions', N'admin.sessions.view', N'View active sessions'),
    (N'admin.view.system.logs', N'admin.logs.view', N'View system logs'),
    (N'admin.status.view', N'admin.status.view', N'View the system status page'),
    (N'admin.maintenance.view', N'admin.maintenance.view', N'View the maintenance page'),
    (N'admin.maintenance.edit', N'admin.maintenance.edit', N'Edit and release maintenance periods'),
    (N'admin.maintenance.bypass', N'admin.maintenance.bypass', N'Bypass the maintenance lockout'),
    (N'admin.restart', N'admin.server.restart', N'Restart the local dev server (dev only)'),
    (N'workitems.view', N'workitems.view', N'View the workitems page'),
    (N'workitems.details.view', N'workitems.details.view', N'View workitem details'),
    (N'workitems.details.view.audit', N'workitems.details.audit.view', N'View the workitem audit trail'),
    (N'workitems.details.view.fields', N'workitems.details.fields.view', N'View extracted fields'),
    (N'workitems.details.view.images', N'workitems.details.images.view', N'View document images'),
    (N'workitems.details.view.confidence', N'workitems.details.confidence.view', N'View extraction confidence scores'),
    (N'workitems.details.view.source_location', N'workitems.details.sources.view', N'View where values were found on the page (needs images.view)'),
    (N'workitems.filter.datetime', N'workitems.filter.date.view', N'Filter by date'),
    (N'workitems.filter.status', N'workitems.filter.status.view', N'Filter by status'),
    (N'workitems.filter.status.deleted', N'workitems.filter.deleted.view', N'Filter for deleted workitems (internal; needs status.view)'),
    (N'workitems.filter.stage', N'workitems.filter.stage.view', N'Filter by process stage'),
    (N'workitems.filter.workitemid', N'workitems.filter.id.view', N'Search by workitem id'),
    (N'workitems.filter.documentfields', N'workitems.filter.docfields.view', N'Filter by document fields'),
    (N'workitems.filter.documentfields.sensitive', N'workitems.filter.docfields.sensitive.view', N'Filter by sensitive document fields (needs docfields.view)'),
    (N'workitems.import.workitem', N'workitems.import.run', N'Import a workitem'),
    (N'workitems.import.preparedaudit', N'workitems.prepared.view', N'View the prepared-documents import and audit page'),
    (N'dashboard.view', N'dashboard.view', N'View the dashboard'),
    (N'api.docs.view', N'api.docs.view', N'View the in-app API documentation'),
    (N'jd.view', N'jd.view', N'View the JD page'),
    (N'reporting.view', N'reporting.view', N'View the reporting page'),
    (N'reporting.export', N'reporting.export', N'Export reports to Excel'),
    (N'reporting.schedule', N'reporting.schedule', N'Schedule reports for email delivery'),
    (N'reporting.sql.run', N'reporting.sql.run', N'Run live read-only SQL in the sandbox'),
    (N'reporting.sql.target.octopus', N'reporting.sql.target.octopus.use', N'Target the Octo runtime DB in the sandbox'),
    (N'reporting.ai.use', N'reporting.ai.use', N'Use the AI assistant'),
    (N'reporting.ai.sql', N'reporting.ai.sql.use', N'Receive AI-drafted SQL (needs sql.run)'),
    (N'reporting.ai.explain_data', N'reporting.ai.explain.use', N'Let the AI run queries and explain results (data egress; needs sql.run)'),
    (N'reporting.admin.sources', N'reporting.sources.manage', N'Manage the data-source registry'),
    (N'reporting.sources.schema', N'reporting.sources.schema.view', N'Browse tables and columns of a source'),
    (N'reporting.semantic.admin', N'reporting.metrics.manage', N'Manage the canonical metrics registry'),
    (N'reporting.source.docprocessing', N'reporting.source.docprocessing.use', N'Use the Document Processing source'),
    (N'reporting.source.workitems', N'reporting.source.workitems.use', N'Use the Workitems (Octo) source'),
    (N'reporting.source.generali.pdqm', N'reporting.source.generali_pdqm.use', N'Use the Generali PDQM source'),
    (N'tenant.ms02.view', N'tenant.ms02.view', N'View the MS02 pilot tenant pages'),
    (N'tenant.ms02.edit', N'tenant.ms02.edit', N'Edit the MS02 pilot tenant data'),
    (N'generali.dashboard.view', N'tenant.generali.view', N'View the Generali dashboard'),
    (N'generali.documentlist.view', N'tenant.generali.documents.view', N'View the Generali document list'),
    (N'generali.importstatus.view', N'tenant.generali.importstatus.view', N'View the Generali import status'),
    (N'generali.additionalservices.view', N'tenant.generali.attendance.view', N'View the attendance page (Zusätzliche Leistungen)'),
    (N'generali.attendance.add', N'tenant.generali.attendance.add', N'Add own attendance records'),
    (N'generali.attendance.add.bypass.deadline', N'tenant.generali.attendance.add.pastdeadline', N'Add attendance records past the deadline'),
    (N'generali.attendance.add.organizational', N'tenant.generali.attendance.add.org', N'Add attendance records for the own organization'),
    (N'generali.attendance.add.transorganizational', N'tenant.generali.attendance.add.all', N'Add attendance records for every organization'),
    (N'generali.attendance.edit.organizational', N'tenant.generali.attendance.edit.org', N'Edit attendance records for the own organization'),
    (N'generali.attendance.edit.transorganizational', N'tenant.generali.attendance.edit.all', N'Edit attendance records for every organization'),
    (N'generali.attendance.delete.organizational', N'tenant.generali.attendance.delete.org', N'Delete attendance records for the own organization'),
    (N'generali.attendance.delete.transorganizational', N'tenant.generali.attendance.delete.all', N'Delete attendance records for every organization'),
    (N'generali.baseservices.view', N'tenant.generali.baseservices.view', N'View the Generali base service records page'),
    (N'generali.baseservices.add', N'tenant.generali.baseservices.add', N'Add own base service records'),
    (N'generali.baseservices.add.bypass.deadline', N'tenant.generali.baseservices.add.pastdeadline', N'Add base service records past the deadline'),
    (N'generali.baseservices.add.organizational', N'tenant.generali.baseservices.add.org', N'Add base service records for the own organization'),
    (N'generali.baseservices.add.transorganizational', N'tenant.generali.baseservices.add.all', N'Add base service records for every organization'),
    (N'generali.baseservices.edit.organizational', N'tenant.generali.baseservices.edit.org', N'Edit base service records for the own organization'),
    (N'generali.baseservices.edit.transorganizational', N'tenant.generali.baseservices.edit.all', N'Edit base service records for every organization'),
    (N'generali.baseservices.delete.organizational', N'tenant.generali.baseservices.delete.org', N'Delete base service records for the own organization'),
    (N'generali.baseservices.delete.transorganizational', N'tenant.generali.baseservices.delete.all', N'Delete base service records for every organization'),
    (N'generali.pdqm.view', N'tenant.generali.pdqm.view', N'View the Generali PDQM records page'),
    (N'generali.pdqm.add', N'tenant.generali.pdqm.add', N'Add own PDQM records'),
    (N'generali.pdqm.add.bypass.deadline', N'tenant.generali.pdqm.add.pastdeadline', N'Add PDQM records past the deadline'),
    (N'generali.pdqm.add.organizational', N'tenant.generali.pdqm.add.org', N'Add PDQM records for the own organization'),
    (N'generali.pdqm.add.transorganizational', N'tenant.generali.pdqm.add.all', N'Add PDQM records for every organization'),
    (N'generali.pdqm.edit.organizational', N'tenant.generali.pdqm.edit.org', N'Edit PDQM records for the own organization'),
    (N'generali.pdqm.edit.transorganizational', N'tenant.generali.pdqm.edit.all', N'Edit PDQM records for every organization'),
    (N'generali.pdqm.delete.organizational', N'tenant.generali.pdqm.delete.org', N'Delete PDQM records for the own organization'),
    (N'generali.pdqm.delete.transorganizational', N'tenant.generali.pdqm.delete.all', N'Delete PDQM records for every organization'),
    (N'generali.projectmanagement.view', N'tenant.generali.projectmanagement.view', N'View the Generali project management records page'),
    (N'generali.projectmanagement.add', N'tenant.generali.projectmanagement.add', N'Add own project management records'),
    (N'generali.projectmanagement.add.bypass.deadline', N'tenant.generali.projectmanagement.add.pastdeadline', N'Add project management records past the deadline'),
    (N'generali.projectmanagement.add.organizational', N'tenant.generali.projectmanagement.add.org', N'Add project management records for the own organization'),
    (N'generali.projectmanagement.add.transorganizational', N'tenant.generali.projectmanagement.add.all', N'Add project management records for every organization'),
    (N'generali.projectmanagement.edit.organizational', N'tenant.generali.projectmanagement.edit.org', N'Edit project management records for the own organization'),
    (N'generali.projectmanagement.edit.transorganizational', N'tenant.generali.projectmanagement.edit.all', N'Edit project management records for every organization'),
    (N'generali.projectmanagement.delete.organizational', N'tenant.generali.projectmanagement.delete.org', N'Delete project management records for the own organization'),
    (N'generali.projectmanagement.delete.transorganizational', N'tenant.generali.projectmanagement.delete.all', N'Delete project management records for every organization'),
    (N'generali.reporting.view', N'tenant.generali.reporting.view', N'View the Generali reporting records page'),
    (N'generali.reporting.add', N'tenant.generali.reporting.add', N'Add own reporting records'),
    (N'generali.reporting.add.bypass.deadline', N'tenant.generali.reporting.add.pastdeadline', N'Add reporting records past the deadline'),
    (N'generali.reporting.edit.organizational', N'tenant.generali.reporting.edit.org', N'Edit reporting records for the own organization'),
    (N'generali.reporting.edit.transorganizational', N'tenant.generali.reporting.edit.all', N'Edit reporting records for every organization'),
    (N'generali.reporting.delete.organizational', N'tenant.generali.reporting.delete.org', N'Delete reporting records for the own organization'),
    (N'generali.reporting.delete.transorganizational', N'tenant.generali.reporting.delete.all', N'Delete reporting records for every organization');
-- A concurrent worktree can land a same-named permission before this rename
-- applies (e.g. #255's tenant-platform work seeding 'tenant.generali.view'
-- ahead of #238 -- spec decision D3: this migration owns the code, the
-- tenant platform finds it in place). Merge such a duplicate's grants onto
-- the row this migration is about to rename into that code, then retire the
-- duplicate, so the rename below never collides on the UNIQUE(Code).
DECLARE @dups TABLE (DupPermID INT PRIMARY KEY, CanonicalPermID INT);
INSERT INTO @dups (DupPermID, CanonicalPermID)
SELECT p.PermissionID, o.PermissionID
FROM @map m
JOIN dbo.Permission p ON p.Code = m.NewCode
JOIN dbo.Permission o ON o.Code = m.OldCode
WHERE m.OldCode <> m.NewCode AND o.PermissionID <> p.PermissionID;
INSERT INTO dbo.AccessProfilePermission (AccessID, PermissionID)
SELECT ap.AccessID, d.CanonicalPermID
FROM dbo.AccessProfilePermission ap
JOIN @dups d ON d.DupPermID = ap.PermissionID
WHERE NOT EXISTS (SELECT 1 FROM dbo.AccessProfilePermission x
                  WHERE x.AccessID = ap.AccessID AND x.PermissionID = d.CanonicalPermID);
INSERT INTO dbo.UserPermissionOverride (UserID, PermissionID, Effect)
SELECT o2.UserID, d.CanonicalPermID, o2.Effect
FROM dbo.UserPermissionOverride o2
JOIN @dups d ON d.DupPermID = o2.PermissionID
WHERE NOT EXISTS (SELECT 1 FROM dbo.UserPermissionOverride x
                  WHERE x.UserID = o2.UserID AND x.PermissionID = d.CanonicalPermID);
DELETE ap FROM dbo.AccessProfilePermission ap JOIN @dups d ON d.DupPermID = ap.PermissionID;
DELETE o2 FROM dbo.UserPermissionOverride o2 JOIN @dups d ON d.DupPermID = o2.PermissionID;
DELETE p FROM dbo.Permission p JOIN @dups d ON d.DupPermID = p.PermissionID;
IF EXISTS (SELECT 1 FROM @map m JOIN dbo.Permission p ON p.Code = m.NewCode
           JOIN dbo.Permission o ON o.Code = m.OldCode WHERE m.OldCode <> m.NewCode AND o.PermissionID <> p.PermissionID)
    THROW 50088, 'permission rename target already exists with a different PermissionID', 1;
UPDATE p SET p.Code = m.NewCode, p.Description = m.NewDescription
FROM dbo.Permission p JOIN @map m ON m.OldCode = p.Code;
UPDATE r SET r.Permission = m.NewCode
FROM dbo.ReportingSources r JOIN @map m ON m.OldCode = r.Permission;
INSERT INTO dbo.Permission (Code, Description)
SELECT 'admin.permissions.edit', 'Edit the permission catalogue (descriptions, add, delete)'
WHERE NOT EXISTS (SELECT 1 FROM dbo.Permission WHERE Code = 'admin.permissions.edit');
INSERT INTO dbo.AccessProfilePermission (AccessID, PermissionID)
SELECT ap.AccessID, np.PermissionID
FROM dbo.AccessProfilePermission ap
JOIN dbo.Permission hp ON hp.PermissionID = ap.PermissionID AND hp.Code = 'admin.profiles.edit'
CROSS JOIN dbo.Permission np
WHERE np.Code = 'admin.permissions.edit'
  AND NOT EXISTS (SELECT 1 FROM dbo.AccessProfilePermission x WHERE x.AccessID = ap.AccessID AND x.PermissionID = np.PermissionID);
GO
