USE [nexora]
GO
DROP TABLE [dbo].[FieldAliases]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FieldAliases](
	[SourceFieldName] [nvarchar](100) NOT NULL,
	[TargetKey] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_FieldAliases] PRIMARY KEY CLUSTERED 
(
	[SourceFieldName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
