USE [nexora]
GO
ALTER TABLE [dbo].[ApiKeys] DROP CONSTRAINT [DF_ApiKeys_CreatedAt]
GO
ALTER TABLE [dbo].[ApiKeys] DROP CONSTRAINT [DF_ApiKeys_Enabled]
GO
DROP TABLE [dbo].[ApiKeys]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ApiKeys](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[KeyHash] [char](64) NOT NULL,
	[ClientCode] [nvarchar](32) NOT NULL,
	[Label] [nvarchar](255) NULL,
	[ProcessList] [nvarchar](max) NOT NULL,
	[Enabled] [bit] NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[LastUsedAt] [datetime2](7) NULL,
 CONSTRAINT [PK_ApiKeys] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_ApiKeys_KeyHash] UNIQUE NONCLUSTERED 
(
	[KeyHash] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[ApiKeys] ADD  CONSTRAINT [DF_ApiKeys_Enabled]  DEFAULT ((1)) FOR [Enabled]
GO
ALTER TABLE [dbo].[ApiKeys] ADD  CONSTRAINT [DF_ApiKeys_CreatedAt]  DEFAULT (sysutcdatetime()) FOR [CreatedAt]
GO
