USE [nexora]
GO
DROP TABLE [dbo].[decapitated_Comment_Mentions]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[decapitated_Comment_Mentions](
	[MentionID] [int] IDENTITY(1,1) NOT NULL,
	[CommentID] [int] NULL,
	[MentionedUserID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MentionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
