USE [nexora]
GO
DROP TABLE [dbo].[decapitated_IndexFieldMappings]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[decapitated_IndexFieldMappings](
	[MappingID] [int] IDENTITY(1,1) NOT NULL,
	[SourceFieldName] [nvarchar](100) NOT NULL,
	[TargetKey] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MappingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
