USE [Generali]
GO
DROP TABLE [dbo].[CategoryTerms]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CategoryTerms](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NameDe] [nvarchar](255) NOT NULL,
	[NameEn] [nvarchar](255) NULL,
	[NameFr] [nvarchar](255) NULL,
	[NameIt] [nvarchar](255) NULL,
 CONSTRAINT [PK_CategoryTerms] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_CategoryTerms_NameDe] UNIQUE NONCLUSTERED 
(
	[NameDe] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
